[paths]
amazon_sales = "app/data/AmazonSaleReport.csv"
international_sales = "app/data/InternationalSaleReport.csv"
sale_report = "app/data/SaleReport.csv"
pl_files = ["app/data/PLMarch2021.csv", "app/data/May2022.csv"]

[ml]
model_type = "RandomForest"
predict_features = ["sku", "date", "ship_state"]
target = "revenue"